finite stochastic language
# number of traces 
6
# trace 0
# probability
10/100
# number of events
3
a
c
b
# trace 1
# probability
15/100
# number of events
3
a
b
c
# trace 2
# probability
40/100
# number of events
2
a
d
# trace 3
# probability
20/100
# number of events
4
a
d
e
d
# trace 4
# probability
10/100
# number of events
6
a
d
e
d
e
d
# trace 5
# probability
5/100
# number of events
8
a
d
e
d
e
d
e
d
