name: Build Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Windows
      run: |
        rustup target add x86_64-pc-windows-gnu
        cargo build --target x86_64-pc-windows-gnu --release
    - name: Run tests
      run: cargo test --verbose
