name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build Linux
      run: cargo build --target x86_64-unknown-linux-gnu --release
    - name: Move Linux
      run: |
        mkdir out
        cp ./target/x86_64-unknown-linux-gnu/release/ebi ./out/Ebi-x86_64-linux
    - uses: actions/upload-artifact@v2  
      with:
        name: Linux
        path: out/Ebi-x86_64-linux
    - name: Build Windows
      run: |
        apt install mingw-w64
        rustup target add x86_64-pc-windows-gnu
        cargo build --target x86_64-pc-windows-gnu --release
    - name: Move Windows
      run: |
        mkdir out
        cp ./target/x86_64-pc-windows-gnu/release/ebi ./out/Ebi-x86_64-windows.exe
