name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: manual
      run: cd manual; cargo run latex manual -o functions.tex; rsvg-convert -f pdf -o graph.pdf graph.svg; lualatex manual.tex; bibtex manual
