name: Run Rust tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --verbose
    - name: commit to Gitlab
      env:
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
      run: |
        git clone https://ci_token:$GITLAB_TOKEN@git.rwth-aachen.de/rwth-bpm/rustlibrary
        cd rustlibrary
        git config user.name "Github auto committer"
        git config user.email "cipipeline@example.com"
        rm -rf src/*
        rm README.md
        rm -rf manual/*
        cp -R -a ../src/. src/
        cp ../README.md README.md
        cp -R -a ../manual/. manual/
        git commit -a -m "github CI"
        git push -f https://ci_token:$GITLAB_TOKEN@git.rwth-aachen.de/rwth-bpm/rustlibrary HEAD:main