name: Run Rust tests

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run tests mixed mode 1
      run: cargo test --verbose
    - name: Run tests mixed mode 2
      run: cargo test --verbose --features exactarithmetic,approximatearithmetic
    - name: Run tests exact mode
      run: cargo test --verbose --features exactarithmetic
    - name: Run tests approximate mode
      run: cargo test --verbose --features approximatearithmetic